@baseUrl = http://localhost:8003

### Listar productos
GET {{baseUrl}}/productos

### Listar productos disponibles
GET {{baseUrl}}/productos/disponibles

### Listar por categoria
GET {{baseUrl}}/productos/categoria/1

### Obtener producto
GET {{baseUrl}}/productos/1

### Crear producto
POST {{baseUrl}}/productos
Content-Type: application/json

{
    "nombre": "Limonada Natural",
    "descripcion": "Bebida natural de limón ",
    "precio": 8000,
    "disponible": true,
    "categoria_id": 1
}

### Actualizar producto
PUT {{baseUrl}}/productos/1
Content-Type: application/json

{
    "nombre": "Hamburguesa Especial",
    "descripcion": "Hamburguesa con queso y tocineta",
    "precio": 28000,
    "disponible": true,
    "categoria_id": 3
}

### Eliminar producto
DELETE {{baseUrl}}/productos/1